project_id = "hcjwjnabysexihsgqffg"

[functions.detect-medical-tasks]
verify_jwt = false

[functions.generate-soap-note]
verify_jwt = false

[functions.generate-questions]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.dust-workflow]
verify_jwt = false
